In [1]:
s = '11'
d = int(s)
print(d)

11


In [2]:
b  = ( int(s,2) )
print(b)

3


### 부동소수점 끼리 연산하기

In [3]:
0.2*3 == 0.6

False

In [4]:
1.2-0.2 == 1.0

True

In [5]:
1.2-0.1 == 1.1

False

In [7]:
def a(x,y, places=7):
    return round(abs(x-y), 7) == 0 

In [9]:
a(3.14,3.14)

True

### 정수와 부동 소수점 메서드

In [10]:
divmod(45, 6)

(7, 3)

In [11]:
round( 113.866, -1)

110.0

In [12]:
round( 113.866, 2)

113.87

### fraction 모듈

In [18]:
from fractions import Fraction

In [21]:
def rounding_floats(number1, places):
    return round(number1, places)

In [33]:
def float_to_fractions(number):
    return Fraction(*number.as_integer_ratio())

In [36]:
def get_denominator(number1, number2):
    a = Fraction(number1, number2)
    return a.denominator

In [39]:
def get_numerator(number1, number2):
    a = Fraction(number1, number2)
    return a.numerator

In [40]:
def test_testing_floats():
    number1 = 1.25
    number2 = 1
    number3 = -1
    number4 = 5/4
    number6 = 6
    assert(rounding_floats(number1, number2)==1.2)
    assert(rounding_floats(number1*10, number3)==10)
    assert(float_to_fractions(number1)==5/4)
    assert(get_denominator(number2, number6)==number6)
    assert(get_numerator(number2, number6)==number2)

In [41]:
test_testing_floats()

### decimal 모듈


In [43]:
sum( 0.1 for i in range(10)) == 1.0

False

In [44]:
from decimal import Decimal
sum( Decimal("0.1") for i in range(10)) == Decimal("1.0")

True

###  2진수, 8진수, 16진수

In [45]:
bin(999)

'0b1111100111'

In [46]:
oct(999)

'0o1747'

In [47]:
hex(999)

'0x3e7'

### 진법 변환

In [48]:
def convert_to_decimal(number, base):
    multiplier, result = 1, 0
    while number > 0 : 
        result += number % 10 * multiplier
        multiplier *= base
        number = number // 10
    return result 

In [59]:
def test_convert_to_decimal():
    number, base = 1001, 2
    assert( convert_to_decimal(number, base) == 9)
    print('테스트 통과')

In [60]:
test_convert_to_decimal()

테스트 통과


In [64]:
def convert_from_decimal_larger_bases(number, base):
    strings = "0123456789ABCDEFGHIJ"
    result = ""
    while number > 0 : 
        digit = number % base
        result = strings[digit] + result
        number = number // base
    return result 

def test_convert_from_decimal_larger_bases():
    number, base = 31, 16
    assert( convert_from_decimal_larger_bases(number, base) == "1F")
    print('테스트 통과')
           
if __name__ == "__main__":
    test_convert_from_decimal_larger_bases()

테스트 통과


In [66]:
def convert_dec_to_any_base_rec(number, base):
    convertString = "0123456789ABCDEF"
    result = ""
    if number < base:
        return convertString[number]
    else:
        return convert_dec_to_any_base_rec(number//base, base)\
            + convertString[number%base]

def test_convert_dec_to_any_base_rec():
    number, base = 9, 2
    assert( convert_dec_to_any_base_rec(number, base) == "1001")
    print('테스트 통과')
           
if __name__ == "__main__":
    test_convert_dec_to_any_base_rec()

테스트 통과


### 최대공약수

In [70]:
def finding_gcd(a, b):
    while(b!=0):
        result = b
        a, b = b, a%b
    return result

def test_finding_gcd():
    number1 = 120
    number2 = 280
    assert(finding_gcd(number1, number2)==40)
    print("테스트 통과!")

if __name__ == "__main__":
    test_finding_gcd()

테스트 통과!


### random 모듈

In [194]:
import random

def testing_random():
    values = [1,2,3,4]
    print(random.choice(values))
    print(random.choice(values))
    print(random.choice(values))
    print(random.sample(values, 2))
    print(random.sample(values, 3))
    
    random.shuffle(values)
    print(values)
    
    print(random.randint(0, 10))
    print(random.randint(0, 10))
    
if __name__ == "__main__":
    testing_random()

2
3
4
[1, 4]
[2, 1, 3]
[2, 4, 3, 1]
7
3


### 피보나치 수열

In [200]:
import math

def find_fibonacci_seq_form(n):
    sq5 = math.sqrt(5)
    phi = (1+sq5)/2
    return int(math.floor(phi**n / sq5))

def test_find_fib():
    n=10
    assert(find_fibonacci_seq_form(n)==55)
    print("테스트 통과!")
    
if __name__ == "__main__":
    
    test_find_fib()

테스트 통과!


In [204]:
def fib_generator():
    a,b = 0,1
    while True:
        yield b
        a, b = b, a+b
        
if __name__ == "__main__":
    temp = fib_generator()
    print(temp)
    print(next(temp))
    print(next(temp))
    print(next(temp))

<generator object fib_generator at 0x0000013B83B94A48>
1
1
2


In [206]:
def fib_generator():
    a,b = 0,1
    while True:
        yield b
        a, b = b, a+b
        
if __name__ == "__main__":
    temp = fib_generator()
    for _ in range(10):
        print(next(temp), end=" ")


1 1 2 3 5 8 13 21 34 55 

### 소수(prime number)

In [215]:
import math
import random

def finding_prime(number):
    num = abs(number)
    if( num < 4) : return True
    
    for x in range(2,num):
        if num % x == 0:
            return False
    return True

def finding_prime_sqrt(number):
    num = abs(number)
    if( num < 4) : return True
    
    for x in range(2, int(math.sqrt(num))+1):
        if num % x == 0:
            return False
    return True

def finding_prime_ferat(number):
    if number <= 102:
        for a in range(2, number):
            if pow(a, number-1, number) != 1:
                return False
        return True
    else:
        for i in range(100):
            a = random.randint(2, number-1)
            if pow(a, number-1, number) != 1:
                return False
        return True

def test_finding_prime():
    number1 = 17
    number2 = 20
    assert(finding_prime(number1) == True)
    assert(finding_prime(number2) == False)
    assert(finding_prime_sqrt(number1) == True)
    assert(finding_prime_sqrt(number2) == False)
    assert(finding_prime_ferat(number1) == True)
    assert(finding_prime_ferat(number2) == False)
    print("테스트 통과!")
    
if __name__ == "__main__":
    test_finding_prime()

테스트 통과!


### 넘파이 패키지

In [216]:
import numpy as np

np.array( ((11,12,13) , (21,22,23) , (31,32,33 )))

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [219]:
import numpy as np
x = np.array( ((11,12,13) , (21,22,23) , (31,32,33 )))
x.ndim

2

In [220]:
x.shape

(3, 3)

In [243]:
import numpy as np

def testing_numpy():
    ax = np.array([1,2,3])
    ay = np.array([3,4,5])
    print(ax)
    print(ax*2)
    print(ax+10)
    print(np.sqrt(ax))
    print(np.cos(ax))
    print(ax-ay)
    print(ax)
    print(np.where(ax>2, ax, 5))
    
    m = np.matrix([ax, ay, ax])
    print(m)
    print(m.T)
    
    grid1 = np.zeros( shape=(10,10), dtype=float)
    grid2 = np.ones( shape=(10,10), dtype=float)
    print(grid1)
    print(grid2)
    print(grid1[1]+10)
    print(grid2[:,2]*2)

if __name__ == "__main__":
    testing_numpy()

[1 2 3]
[2 4 6]
[11 12 13]
[1.         1.41421356 1.73205081]
[ 0.54030231 -0.41614684 -0.9899925 ]
[-2 -2 -2]
[1 2 3]
[5 5 3]
[[1 2 3]
 [3 4 5]
 [1 2 3]]
[[1 3 1]
 [2 4 2]
 [3 5 3]]
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
[10. 10. 10. 10. 10. 10. 10. 10. 10. 10.]
[2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]


In [252]:
import numpy
import time

def trad_version():
    t1 = time.time()
    X = range(10000000)
    Y = range(10000000)
    Z = []
    for i in range(len(X)):
        Z.append(X[i] + Y[i])
    
    return time.time() - t1

def numpy_version():
    t1 = time.time()
    X = numpy.arange(10000000)
    Y = numpy.arange(10000000)
    Z = X + Y
   
    return time.time() - t1

if __name__ == "__main__":
    print(trad_version())
    print(numpy_version())

4.62026047706604
0.03125739097595215


In [258]:
l=[]
type(l)

s=""
type(s)

t = ()
type(t)

ba = bytearray(b"")
type(ba)

b = bytes([])
type(b)

bytes

### 깊은 복사와 슬라이싱 연산

#### 가변성

In [259]:
myList = [1,2,3,4]
newList = myList[:]
newList2 = list(myList)

In [260]:
print(id(myList), id(newList))

1355146047944 1355145940872


In [261]:
people = {"버피", "에인절", "자일스"}
slayers = people.copy()
slayers.discard("자일스")
slayers.remove("에인절")
slayers

{'버피'}

In [262]:
people

{'버피', '에인절', '자일스'}

In [263]:
myDict = {"안녕":"세상"}
newDict = myDict.copy()

### 슬라이싱 연산자

In [268]:
word = "뱀파이어를 조심해!"
word[-1]
word[-2]
word[-2:]
word[:-2]
word[-0]

'뱀'

### 튜플

In [273]:
t1 = 123, '안녕!'
t1[1]

'안녕!'

In [274]:
t1

(123, '안녕!')

In [276]:
t2 = t1, (1,2,3,4,5)
t2

((123, '안녕!'), (1, 2, 3, 4, 5))

In [277]:
empty = ()

In [278]:
t1 = '안녕'

In [286]:
t1 = ('안','녕')

In [287]:
len(empty)

0

In [289]:
t1

('안', '녕')

### 튜플 언패킹

In [291]:
a,b,c = (1,2,3)

In [292]:
print(a,b,c)

1 2 3


In [293]:
x, *y = (1,2,3,4)

In [294]:
x

1

In [295]:
y

[2, 3, 4]

In [296]:
*x, y = (1,2,3,4)

In [297]:
y

4

In [298]:
x

[1, 2, 3]

### 네임드 튜플

In [301]:
import collections

Person = collections.namedtuple('Person', 'name age gender')
p = Person('아스틴', 30, '남자')
p

Person(name='아스틴', age=30, gender='남자')

In [302]:
p[0]

'아스틴'

In [303]:
p[1]

30

In [304]:
p.name

'아스틴'

In [305]:
p.age

30

In [306]:
p.gender

'남자'

In [307]:
p.age = 20

AttributeError: can't set attribute

### 리스트 컴프리헨션

In [309]:
a = [y for y in range(10)]

In [310]:
a

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [313]:
a = [y for y in range(1900,1940) if y%4 == 0 ]

In [314]:
a

[1900, 1904, 1908, 1912, 1916, 1920, 1924, 1928, 1932, 1936]

In [315]:
b = [ 2**i for i in range(13) ]

In [316]:
b

[1, 2, 4, 8, 16, 32, 64, 128, 256, 512, 1024, 2048, 4096]

### 바이트와 바이트배열

In [317]:
blist = [1, 2, 3, 255]

In [318]:
the_bytes = bytes(blist)

In [319]:
the_bytes

b'\x01\x02\x03\xff'

In [320]:
the_byte_array = bytearray(blist)

In [324]:
the_byte_array[1] = 127
the_byte_array

bytearray(b'\x01\x7f\x03\xff')

In [321]:
the_byte_array

bytearray(b'\x01\x02\x03\xff')

In [322]:
the_bytes[1] = 127

TypeError: 'bytes' object does not support item assignment

### 비트와 비트연산자

In [325]:
x = 4
1 << x

16

In [326]:
x = 8
x & (x-1)

0

In [ ]:
x = 6
x & (x-1)

In [329]:
def bit_count(x):
    count = 0
    for i in range(32):
        if  x & (1<<i) != 0:
            count += 1
    return count

def bit_count_new(x):
    count = 0
    while x != 0 :
        x = x & (x-1)
        count += 1
    return count

x = 0x12345678
print(bit_count_new(x))

13
