In [1]:
s = '11'
d = int(s)
print(d)

11


In [5]:
b = (int(s,2))
print(b)

3


### 부동소수점 끼리 연산하기

In [6]:
0.2*3 == 0.6  #부동소수점은 같냐 다르냐 비교하면 안된다

#진수를 변환하면 무한 소수가 될 확률이 크다. 
#대소비교는 가능해도 ==, !=는 안된다

False

In [7]:
1.2  - 0.2 == 1.0

True

In [10]:
1.2  - 0.1 == 1.1

False

In [11]:
0.1*0.1 == 0.01

False

In [13]:
def a(x, y, places=7):
    return round(abs(x-y), places)==0
a(3.14, 3.14)

#round(number, place)
# round()함수에서 place가 생략되면 소수 첫째 자리에서 반올림한다.
# 소수 place번째 자리에서 반올림한다.

True

### 정수와 부동 소수점 메서드

In [14]:
divmod(45, 6)

(7, 3)

In [15]:
round(113.866, -1)
#정수 첫번째 자리에서 반올림 하라는 뜻. 이렇게 거의 사용 안함

110.0

In [17]:
round(113.866, 2)
#소숫점 2번째 자리에서 반올림

113.87

### fraction 모듈 

In [32]:
from fractions import Fraction


In [33]:
def rounding_floats(number1, places):
    return round(number1, places)

In [61]:
def float_to_fractions(number):
    return Fraction(*number.as_integer_ratio())
#이렇게 임포트한 Fraction 사용할 때는 number를 저렇게 바꿔서 넣어줘라 (형태 암기)


In [62]:
def get_denominator(number1, number2):
    a = Fraction(number1, number2)
    return a.denominator  #분모 추출

In [63]:
def get_numerator(number1, number2):
    a = Fraction(number1, number2)
    return a.numerator  #분자 추출

In [38]:
def test_testing_floats():
    number1 = 1.25
    number2 = 1
    number3 = -1
    number4 = 5/4
    number6 = 6
    print(rounding_floats(number1, number2) == 1.2)


In [39]:
test_testing_floats()

True


In [48]:
def test_testing_floats():
    number1 = 1.25
    number2 = 1
    number3 = -1
    number4 = 5/4
    number6 = 6
    assert(rounding_floats(number1, number2) == 1.2)
# assert로 ()하면 true라면 아무일 없이 통과된다. false라면 에러뜬다

In [49]:
test_testing_floats()

In [57]:
def test_testing_floats():
    number1 = 1.25
    number2 = 1
    number3 = -1
    number4 = 5/4
    number6 = 6
    assert(rounding_floats(number1, number2) == 1.5)# 1.5라서 에러날 것이다
# assert로 ()하면 true라면 아무일 없이 통과된다. false라면 에러뜬다

In [58]:
test_testing_floats()

AssertionError: 

In [64]:
def test_testing_floats():
    number1 = 1.25
    number2 = 1
    number3 = -1
    number4 = 5/4
    number6 = 6
    assert(rounding_floats(number1, number2) == 1.2)
    assert(rounding_floats(number1*10, number3) == 10)
    assert(float_to_fractions(number1) == 5/4)
    assert(get_denominator(number2, number6)==number6) 
    assert(get_numerator(number2, number6)==number2) 

In [65]:
test_testing_floats()

### decimal 모듈

In [67]:
sum (0.1 for i in range(10)) # 1이 안나온다! 0.1이 우리가 아는 0.1이 아니다

0.9999999999999999

In [68]:
sum (0.1 for i in range(10)) == 1.0 #위에서 0.1의 합이 0.99999999... 이기 때문

False

In [70]:
from decimal import Decimal 
sum (Decimal("0.1") for i in range(10)) == Decimal("1.0")
#Decimal 모듈 사용해서 값을 비교하게 만들 수 있다.
#하지만 위험성이 있으므로 지양해야함.

True

### 2진수, 8진수, 16진수 

In [72]:
bin(999) #0b로 출발하는게 2진수이다

'0b1111100111'

In [73]:
oct(999) #0o로 출발하는건 8진수

'0o1747'

In [74]:
hex(999) #0x는 16진수

'0x3e7'

### 진법 변환 

In [75]:
def convert_to_decimal(number, base):
    multiplier, result = 1,0
    while number > 0:
        result += number % 10 * multiplier
        multiplier *= base
        number = number // 10
    return result


In [76]:
convert_to_decimal(11,2)

3

In [86]:
def test_convert_to_decimal():
    number, base = 1001, 2
    assert( convert_to_decimal(number, base) == 9 )
    print('테스트 통과')

In [87]:
test_convert_to_decimal()

테스트 통과


In [88]:
def test_convert_to_decimal():
    number, base = 1001, 3
    assert( convert_to_decimal(number, base) == 9 )
    print('테스트 통과')

In [89]:
test_convert_to_decimal()

AssertionError: 

In [96]:
def convert_from_decimal_larger_bases(number, base):
    strings = "0123456789ABCDEFGHIJ"
    result = ""
    
    while number > 0:
        digit = number% base #여기서는 나머지를 찾아서
        result = strings[digit] + result  # 위의 strings의 해당 인덱스값을 더해
        number = number // base # 몫을 찾아서 위의 digit 값 구하는 것 반복
    return result

def test_convert_from_decimal_larger_bases():
    number, base = 31, 16
    assert( convert_from_decimal_larger_bases(number, base) == "1F" )
    print('테스트 통과')
    
if __name__ == "__main__":
    test_convert_from_decimal_larger_bases()

테스트 통과


In [97]:
test_convert_from_decimal_larger_bases()

테스트 통과


In [107]:
def convert_dec_to_any_base_rec(number, base):
    convertString = "0123456789ABCDEF"
    result = ""
    if number < base:
        return convertString[number]
    else:
        return convert_dec_to_any_base_rec(number // base, base) \
            + convertString[number%base]

def test_convert_dec_to_any_base_rec():
    number, base = 9, 2
    assert( convert_dec_to_any_base_rec(number, base) == "1001" )
    print('테스트 통과')
    
if __name__ == "__main__":
    test_convert_dec_to_any_base_rec()
    # if __name__ == "__main__" : 은 메인함수의 선언, 시작을 의미한다. 
    # 파이썬에서 __name__변수는 내부적으로 사용되는 특별한 변수이름이다
    # 직접 호출되어 사용될 때는 그 자체로 기능을 수행하지만
    # 동시에 다른 모듈에서 필요한 함수 등을 제공할 수도 있다

테스트 통과


### 최대공약수 

In [121]:
def finding_gcd(a,b):
    while(b!=0):
        result = b
        a,b = b, a%b
    return result

def test_finding_gcd():
    number1 = 21
    number2 = 12
    assert(finding_gcd(number1, number2) == 3)
    print('테스트 통과')
    
if __name__ == '__main__':
    test_finding_gcd()

테스트 통과


In [122]:
finding_gcd(21, 12)

3

In [123]:
test_finding_gcd()

테스트 통과


In [124]:
def finding_gcd(a,b):
    while(b!=0):
        result = b
        a,b = b, a%b
    return result

def test_finding_gcd():
    number1 = 280 #꼭 앞에 숫자가 커야하는 것은 아니다. 
    number2 = 120
    assert(finding_gcd(number1, number2) == 40)
    print('테스트 통과')
    
if __name__ == '__main__':
    test_finding_gcd()

테스트 통과


###  random 모듈

In [171]:
import random

def testing_random():
    values = [1,2,3,4]
    print(random.choice(values)) #하나 선택
    print(random.choice(values))
    print(random.choice(values))
    print(random.sample(values,2)) #여러개 선택
    print(random.sample(values,3))
    
    print(values)
    
    random.shuffle(values) # 값을 섞는것
    print(values)
    
    print(random.randint(0,10)) #0이상 10이하
    print(random.randint(0,10))
    print(random.randint(0,10))
    
    
if __name__ == '__main__':
    testing_random()

3
1
1
[1, 4]
[4, 3, 2]
[1, 2, 3, 4]
[3, 1, 2, 4]
8
0
3


###  피보나치 수열

In [174]:
import math

def find_fibonacci_seq_form(n):
    sq5 = math.sqrt(5)
    phi = (1+sq5)/2
    return int(math.floor(phi**n / sq5 ))

def test_find_fib():
    n = 10
    assert(find_fibonacci_seq_form(n) == 55)
    print('테스트 통과')
    
    
if __name__ == '__main__':
    test_find_fib()
    

테스트 통과


In [170]:
def fib_generator():
    a, b = 0, 1
    while True: 
        yield b  #yield 들어가는 것을 제너레이터라고 부른다. 파이썬 중급문법
        a, b = b , a+b
        
if __name__ == "__main__":
    temp = fib_generator()
    for _ in range(10)
    print(temp)
    print(next(temp)) #첫번째를 순회한다
    print(next(temp))
    print(next(temp)) # 위 함수에는 return없고 yield가 있다. yield가 있으면 값을 넘겨주고도 함수가 끝나지 않는다. yield에서 멈추는 것.
    #즉 위 함수는 안끝난다. 계속 next호출 할 때마다 뭔가를 생성한다. 그래서 제너레이터라고 부르는 것
    #제너레이터를 사용한다면 스레드를 사용하지 않고도 스레드 효과를 낸다.

<generator object fib_generator at 0x000001A8416BDF48>
1
1
2


In [177]:
def fib_generator():
    a, b = 0, 1
    while True: 
        yield b  
        a, b = b , a+b
        
if __name__ == "__main__": # 이 코드를 다른데에서 import 할 수 있는데 그 때는 __main__이 아닌 다른 네임이 나온다. 
                            # 그래서 이 파일에서 돌 때 내 코드에서만 돌린다는 test코드라는 뜻이다.
    temp = fib_generator()
    for _ in range(10): # 값을 무시하고 싶을 때 _ (언더스코어) 사용한다.
        print(next(temp), end=' ') 
   

1 1 2 3 5 8 13 21 34 55 

### 소수 (prime number)

In [190]:
import math
import random

def finding_prime(number):
    num = abs(number) # 기본적으로 양의 정수 쓰기 때문에 음수 넘어오면 바꿔주는 것
    if (num < 4 ): # 4 미만의 수들이 오면 계산할 필요가 없기 때문에 
        return True 
    for x in range(2, num): # 1로 나눌 필요는 없으니 2부터, 자기 자신으로도 나누지 않아야 하니까 num 까지
        if num % x == 0: #나누어 떨어지는 경우 소수가 아니다
            return False 
    return True # 이 경우 소수다

def finding_prime_sqrt(number):
    num = abs(number) 
    if (num < 4 ): 
        return True
    
    for x in range(2, int(math.sqrt(num)) + 1):
        if number % x == 0: 
            return False 
    return True
                   
def finding_prime_fermat(number): #페르마의 공식을 이용한 함수다.
    if number <= 102:
        for a in  range(2, number): 
            if pow(a, number-1, number) != 1:  # 제곱수를 사용하고 있다
                return False
        return True
    else: 
        for i in range(100):
            a = random.randint(2, number-1)
            if pow(a, number-1, number) != 1:
                return False
        return True

def test_finding_prime():
    number1 = 17
    number2 = 20
    assert(finding_prime(number1) == True)
    assert(finding_prime(number2) == False)
    assert(finding_prime_sqrt(number1) == True)
    assert(finding_prime_sqrt(number2) == False)
    assert(finding_prime_fermat(number1) == True)
    assert(finding_prime_fermat(number2) == False)
    print('테스트 성공')

    
if __name__ == "__main__":
    test_finding_prime()

테스트 성공


### 넘파이 패키지

In [192]:
import numpy as np

np.array(((11,12,13), (21,22,23), (31,32,33))) # 배열 생성. 배열은 인접메모리. array라고 쓴다.

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [195]:
x = np.array(((11,12,13), (21,22,23), (31,32,33)))
x.ndim #2차원배열이기 때문에 2가 나온다

2

In [197]:
x.shape #형상이 나온다. 어려운 딥러닝에서는 5차원까지 쓴다

(3, 3)

In [211]:
import numpy as np

def testing_numpy():
    ax  = np.array([1,2,3])
    ay  = np.array([3,4,5])
    print(ax)
    print(ax*2) #브로드캐스터. 2가 모든 원소에 곱해진다. 3개 열에 배열처럼 확장된다. 하나의 원소가 있다고 하더라도 각 원소에 곱해짐.
    print(ax+10) #모든 원소에 10이 더해짐
    print(np.sqrt(ax))
    print(np.cos(ax))
    print(ax-ay) # 각각 원소 끼리 사칙연산이 실행됨
    print(np.where(ax<2, ax, 10)) # 조건에 따라 값을 바꿔라
    
    m = np.matrix([ax, ay, ax])
    print(m) #2차원 배열이 나온다. (행렬)
    print(m.T) # T 전치 행렬 . 행과 열을 바꾸는 것이 전치
    
    grid1 = np.zeros( shape=(10,10), dtype = float) # 0으로 채우는 것
    grid2 = np.ones( shape=(10,10), dtype = float) #1로 채우는 것
    print(grid1) #마방진 만들때 리스트보다 np쓰면 더 간단
    print(grid2)
    print(grid1[1]+10) # 1행을 뽑아내서 10을 더한다
    print(grid2[:,2]*2) #모든행의 2번열을 뽑아서 2를 곱한것. 출력값이 보이긴 저래도 열을 뽑아낸 것이다.
    

if __name__ == "__main__":
    testing_numpy()

[1 2 3]
[2 4 6]
[11 12 13]
[1.         1.41421356 1.73205081]
[ 0.54030231 -0.41614684 -0.9899925 ]
[-2 -2 -2]
[ 1 10 10]
[[1 2 3]
 [3 4 5]
 [1 2 3]]
[[1 3 1]
 [2 4 2]
 [3 5 3]]
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
[10. 10. 10. 10. 10. 10. 10. 10. 10. 10.]
[2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]


In [215]:
import numpy
import time #시간과 관련된 것은 time을 임포트 해라

def trad_version():
    t1 = time.time() # 현재시간을 뽑아내는 것
    X = range(10000000)
    Y = range(10000000)
    Z = []
    for i in range(len(X)):
        Z.append(X[i]+Y[i])
        
    return time.time() - t1 # 얼마나 시간 걸렸는지 체크할 수 있다

    print(t1) # 현재시간 볼 수 있다. 초단위로 시간 나온다. 에포크가 나온다. 

if __name__ == "__main__":
    print(trad_version() )

4.390814781188965


In [217]:
import numpy
import time 

def numpy_version(): # numpy가 훨씬 빠르다
    t1 = time.time() 
    X = numpy.arange(10000000)
    Y = numpy.arange(10000000)
    Z = X + Y
        
    return time.time() - t1 # 얼마나 시간 걸렸는지 체크할 수 있다

    print(t1) 

if __name__ == "__main__":
    print(numpy_version() )

0.05696606636047363


In [240]:
l = []
type(l)
s = ''
type(s)
t = ()
type(t)
ba = bytearray(b"")
type(ba)
b = bytes([])
type(b)

bytes

### 깊은 복사와 슬라이싱 연산 

####  가변성

In [221]:
myList = [1,2,3,4]
newList = myList[:] # deepCopy
newList2 = list(myList) #deepCopy

In [223]:
print(id(myList), id(newList), id(newList2))

1822184977288 1822184767688 1822185044168


In [230]:
people = {"버피", "에인절", "자일스"} # 집합, 중복 허용하지 않음. 
slayers = people.copy()
slayers.discard("자일스")
slayers.remove("에인절")
slayers


{'버피'}

In [231]:
people

{'버피', '에인절', '자일스'}

In [232]:
myDict = {"안녕": "세상"}
myDict = myDict.copy() #deepCopy

In [233]:
import copy
myObj = " 다른 어떤 객체"
new

NameError: name 'new' is not defined

###  슬라이싱 연산자

In [237]:
word = "뱀파이어를 조심해!"
word[-1] #가장 끝 문자를 추출
word[-2] # 끝에서 2번째 문자 추출
word[-2:]
word[:-2]
word[-0]

'뱀'

### 튜플 

In [242]:
t1 = 123, '안녕!'
t1
t1[1]

'안녕!'

In [243]:
t2 = t1, (1,2,3,4,5)
t2

((123, '안녕!'), (1, 2, 3, 4, 5))

In [244]:
empty = ()

In [245]:
t1 = "안녕"

In [248]:
t1 = ("안녕",)
len(empty)

0

In [249]:
len(t1)

1

### 튜플 언패킹

In [250]:
a,b = (1,2,3) # 튜플과 value 변수가 같은 수로 있어야 한다 . 

ValueError: too many values to unpack (expected 2)

In [251]:
a,b,c = (1,2,3) # 각각 변수에 들어가는 것을 튜플 언패킹이라고 한다

In [252]:
print(a,b,c)

1 2 3


In [253]:
x, *y = (1, 2, 3, 4) # *를 붙이면 나머지를 다 받아줘라는 의미

In [254]:
print(x, y) # y에는 리스트로 들어가게 된다.

1 [2, 3, 4]


In [255]:
*x, y = (1, 2, 3, 4) # 앞에도 붙일 수 있다. 4가 y로 고정된다. 

In [256]:
print(x, y) 

[1, 2, 3] 4


### 네임드 튜플

In [258]:
import collections

Person = collections.namedtuple('Person', 'name age gender') # namedtuple 사용하면 이름으로 접근 가능
p = Person('아스틴', 30, '남자') # value에 이름을 지정해 줄 수 있다.
p

Person(name='아스틴', age=30, gender='남자')

In [259]:
p[0]

'아스틴'

In [260]:
p.name

'아스틴'

In [261]:
p.age

30

In [263]:
p.gender

'남자'

In [265]:
p.age = 20 # 튜플은 immutable객체이기 때문에 수정할 수 없다.

AttributeError: can't set attribute

### 리스트 컴프리헨션 

In [269]:
a = [ y for y in range(10)]

In [270]:
a

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [275]:
a = [ y for y in range(1900, 1940) if y%4 == 0]

In [276]:
a

[1900, 1904, 1908, 1912, 1916, 1920, 1924, 1928, 1932, 1936]

In [277]:
b = [ 2**i for i in range(13)]

In [278]:
b

[1, 2, 4, 8, 16, 32, 64, 128, 256, 512, 1024, 2048, 4096]

### 바이트와 바이트 배열

In [288]:
blist = [1,2,3,255] # 양의 숫자에서 byte에 들어갈 수 있는 최댓값은 255, 123 255짜리 배열이 된 것이다.
the_bytes = bytes(blist) # 불변이다. 
the_bytes
the_bytes[1] = 2 # 에러난다

TypeError: 'bytes' object does not support item assignment

In [293]:
the_byte_array = bytearray(blist)
the_byte_array # 가변객체다
the_byte_array[2] = 127
the_byte_array # 바뀐다.

bytearray(b'\x01\x02\x7f\xff')

### 비트와 비트 연산자


In [294]:
x = 4
1 << x

16

In [295]:
x = 8
x & (x-1)

0

In [302]:
def bit_count(x):
    count = 0
    for i in range(32):
        if x & (1<<i) != 0:
            count+=1
    return count

x = 0x12345678
print(bit_count(x))


13


In [303]:
def bit_count_new(x): # 위 보다 빠르다. Hamming Weight 로직
    count = 0
    while x != 0:
        x = x & (x-1)
        count+=1
    return count

x = 0x12345678
print(bit_count_new(x))


13
